### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alexpessoajr**

### CODE REVIEW

**Comment by victorlaerte** [comment]
oiaaaaaaaaaaaaaaaaa Rhynoooooooooooooo! 🤣

**Comment by paulorec** [comment]
![](http://www.rootingforrhino.org/rhinofiles/image/rhinos/isolated_rhinos_white.png?raw=true

**Comment by interaminense** [comment]
Image of Yaktocat

**Comment by paulorec** [comment]
rhynooooooo :)

**Comment by embatbr** [comment]
hahaha
fdp

**Comment by embatbr** [comment]
boot, emagreceu ou isso eh foto antiga?

**Comment by paulorec** [comment]
kkkkkkkkkkkkkkk

**Comment by paulorec** [comment]
:heart: we love you rhyno

**Comment by alexpessoajr** [comment]
Rhinoo :heart: :rhinoceros:

**Comment by inacionery** [comment]
Hahahhahahah

**Pull request closed without merging**
